apiVersion: apps/v1
kind: Deployment
metadata:
  name: giftsend
  labels:
    app: giftsend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: giftsend
  template:
    metadata:
      labels:
        app: giftsend
    spec:
      containers:
        - name: giftsend
          image: username/giftsend:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5